sudo: required
dist: trusty
language: c

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-add-repository -y ppa:vala-team/ppa
  - sudo apt-add-repository -y ppa:gnome3-team/gnome3-staging
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1397BC53640DB551 || true
  - sudo apt-get -qq update
  - sudo apt-get -qq install libgee-0.8-dev libgtk-3-dev valac

script:
  - ./waf configure --prefix=/usr
  - ./waf build
  - ./waf install --destdir=dest

addons:
  apt:
    packages:
      - intltool
      # - libgee-0.8-dev
      # - libgtk-3-dev
      - libxml2-utils
      - libxmmsclient-glib-dev
      # - valac

notifications:
  email:
    recipients:
      - dsvensson@gmail.com
    on_success: change
    on_failure: always
