Import('*')

sources = Split("""
    sv.po
    en.po
    de.po
    nl.po
""")


if env.get('HAVE_MSGFMT'):
    for po in sources:
        mo = env.MsgFmt(po)
        env.InstallLocale(mo[0].attributes.install_path, mo)
