Import('env')

lst = Split("""
	abraca.svg
	abraca-128.png
	abraca-playlist-22.png
	abraca-collection-22.png
	abraca-rating-rated.png
	abraca-rating-unrated.png
""")

images, header, vapi = env.GdkPixBufCSource('abraca_images', lst)

env.Append(CPPPATH = Dir('.'))
env.Append(VALAPKGPATH = Dir('.'))
env.Append(VALAPKGS = ['abraca_images'])

Export('images')
