Import('env')

images = Split("""
	abraca.svg
	abraca-128.png
	abraca-playlist-22.png
	abraca-collection-22.png
""")

env.Alias('install',
	env.Install('$DATADIR/pixmaps', images)
)

env.Alias('install',
	env.Install('$DATADIR/applications', 'abraca.desktop')
)
