Import('env')
Import('images')
Import('ui')

vala_sources = """
    abraca.vala
    client.vala
    config.vala
    dragdroptarget.vala
    main_hpaned.vala
    main_window.vala
    medialib.vala
    right_hpaned.vala
    stock.vala
    toolbar.vala
    transform.vala
    treerow_map.vala
    volume_button.vala
""".split()

types_sources = """
    types/configurable.vala
    types/selected_rows_mixin.vala
""".split()

widgets_sources = """
    widgets/cellrenderercollection.vala
    widgets/cellrenderertogglepixbuf.vala
    widgets/rating_entry.vala
    widgets/prettylabel.vala
""".split()

components_sources = """
    components/collections/collections_model.vala
    components/collections/collections_view.vala

    components/filter/filter_editor.vala
    components/filter/filter_model.vala
    components/filter/filter_view.vala

    components/playlist/playlist_model.vala
    components/playlist/playlist_view.vala
    components/playlist/playlist_widget.vala

    components/server/server_browser.vala
    components/server/server_model.vala
""".split()

gladeui_sources = """
    ../gladeui/glade-abraca.vala
""".split()

sources = env.Vala(vala_sources + types_sources + widgets_sources + components_sources + gladeui_sources)
gladeui = sources.pop()

prog = env.Program('abraca', sources + [images, ui], install=True)

Export('sources')
Export('gladeui')

env.Append(CPPPATH = ['utils'])
